# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-11 14:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='County',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[(1, 'Kajiado'), (10, 'Marsabit'), (9, 'Mandera'), (8, 'Garissa'), (7, 'Laikipia'), (6, 'Nakuru'), (4, 'Bomet'), (14, 'Kirinyaga')], max_length=2)),
                ('code', models.IntegerField()),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('gender', models.CharField(blank=True, max_length=40, null=True)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('arrival', models.DateTimeField(auto_now=True, null=True)),
                ('departure', models.DateTimeField(auto_now_add=True, null=True)),
                ('county', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='visitor.County')),
            ],
            options={
                'ordering': ['-departure', '-arrival'],
            },
        ),
    ]
