# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-09 12:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitor', '0002_auto_20180330_1722'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='visitor',
            options={'ordering': ['id']},
        ),
        migrations.AddField(
            model_name='visitor',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='visitor',
            name='gender',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
