# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-11 14:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitor', '0002_auto_20180411_1732'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='visitor',
            options={'ordering': ['id']},
        ),
        migrations.RemoveField(
            model_name='visitor',
            name='departure',
        ),
        migrations.AlterField(
            model_name='visitor',
            name='arrival',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
