# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-12 05:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('visitor', '0004_visitor_departure'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.IntegerField()),
                ('rate_per_day', models.DecimalField(decimal_places=2, max_digits=6)),
                ('room_type', models.CharField(choices=[('SR', 'SingleRoom'), ('DR', 'DoubleRoom'), ('ME', 'MasterEnsuite'), ('EW', 'ExecutiveWing')], default='SR', max_length=20)),
                ('occupancy', models.CharField(choices=[('VA', 'Vacant'), ('OC', 'Occupied')], default='VA', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=30)),
                ('amount_charged', models.DecimalField(decimal_places=2, max_digits=6)),
                ('service_type', models.CharField(choices=[('LR', 'Laundry'), ('RM', 'Rooms'), ('WF', 'Wifi')], default='RM', max_length=10)),
                ('rooms', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='visitor.Room')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=6)),
                ('rooms', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='visitor.Room')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='visitor.Service')),
            ],
        ),
        migrations.AddField(
            model_name='visitor',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='visitor.Room'),
        ),
        migrations.AddField(
            model_name='visitor',
            name='service',
            field=models.ManyToManyField(to='visitor.Service'),
        ),
    ]
