# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-26 05:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitor', '0008_auto_20180426_0829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='county',
            name='code',
            field=models.IntegerField(choices=[('1', 'Kajiado'), ('10', 'Marsabit'), ('9', 'Mandera'), ('8', 'Garissa'), ('7', 'Laikipia'), ('6', 'Nakuru'), ('4', 'Bomet'), ('14', 'Kirinyaga')]),
        ),
        migrations.AlterField(
            model_name='county',
            name='name',
            field=models.CharField(max_length=10),
        ),
    ]
