# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-26 06:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitor', '0015_visitor_county'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='room_type',
            field=models.CharField(choices=[('SR', 'SingleRoom'), ('DR', 'DoubleRoom'), ('ME', 'MasterEnsuite'), ('EW', 'ExecutiveWing')], max_length=20),
        ),
    ]
