# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-26 06:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitor', '0016_auto_20180426_0907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='county',
            name='name',
            field=models.CharField(choices=[('1', 'Kajiado'), ('2', 'Marsabit'), ('3', 'Mandera'), ('4', 'Garissa'), ('5', 'Laikipia'), ('6', 'Nakuru'), ('7', 'Bomet'), ('8', 'Kirinyaga')], max_length=10),
        ),
    ]
