# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-26 07:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitor', '0017_auto_20180426_0910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='county',
            name='name',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='room',
            name='occupancy',
            field=models.CharField(max_length=1),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_type',
            field=models.CharField(max_length=20),
        ),
    ]
