# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-26 08:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitor', '0020_auto_20180426_1138'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='occupancy',
            name='room',
        ),
        migrations.AddField(
            model_name='room',
            name='occupancy',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.DeleteModel(
            name='Occupancy',
        ),
    ]
