# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-26 09:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitor', '0021_auto_20180426_1154'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitor',
            name='room_available',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
