# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-26 09:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visitor', '0022_visitor_room_available'),
    ]

    operations = [
        migrations.RenameField(
            model_name='visitor',
            old_name='room_available',
            new_name='available',
        ),
    ]
