# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-26 09:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitor', '0023_auto_20180426_1203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='county',
            name='name',
            field=models.CharField(choices=[('1', 'Kajiado'), ('2', 'Marsabit'), ('3', 'Mandera'), ('4', 'Garissa'), ('5', 'Laikipia'), ('6', 'Nakuru'), ('7', 'Bomet'), ('8', 'Kirinyaga')], max_length=10),
        ),
        migrations.AlterField(
            model_name='room',
            name='occupancy',
            field=models.CharField(choices=[('V', 'Vacant'), ('O', 'Occupied')], default='V', max_length=1),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_type',
            field=models.CharField(choices=[('SR', 'SingleRoom'), ('DR', 'DoubleRoom'), ('ME', 'MasterEnsuite'), ('EW', 'ExecutiveWing')], max_length=20),
        ),
    ]
