# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-26 09:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('visitor', '0025_auto_20180426_1256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitor',
            name='available',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='visitor.Availability'),
        ),
    ]
